#+TITLE: Tabbar Ruler
#+AUTHOR: Matthew L. Fidler
#+DATE: Monday, Oct 18 2010
#+OPTIONS: num:t
#+STARTUP: content

A modernised tabbar with ruler.

#+ATTR_HTML: title="screenshot"
[[https://www.google.com][file:https://raw.githubusercontent.com/rhoit/tabbar-ruler.el/dump/screenshots/01.png]]

[[file:tabbar-ruler.el][tabbar-ruler.el]] is an emacs package that allows both the tabbar and
the ruler to be used together. In addition it allows auto-hiding of
the menu-bar and tool-bar.

Appearance originally created on reverse engineering /Aquaemacs/, now
improved too looks and feel of modern GUI.

* Getting it
** Requirements

   | package    | version  |
   |------------+----------|
   | emacs      | >= 23    |
   | [[https://github.com/dholm][tabbar]]     | >= 2.0.1 |
   | [[https://github.com/milkypostman/powerline][powerline]]  | >= 2.3   |
   | [[https://github.com/ryuslash/mode-icons][mode-icons]] | >= 0.10  |

   /tabbar-ruler/ package can be found are *el-get* and *MELPA*.

** Manual
   To use  library in your load path and use

   #+BEGIN_SRC emacs-lisp
     (setq tabbar-ruler-global-tabbar t)    ; get tabbar
     (setq tabbar-ruler-global-ruler t)     ; get global ruler
     (setq tabbar-ruler-popup-menu t)       ; get popup menu.
     (setq tabbar-ruler-popup-toolbar t)    ; get popup toolbar
     (setq tabbar-ruler-popup-scrollbar t)  ; show scroll-bar on mouse-move
     (require 'tabbar-ruler)
   #+END_SRC

* Configuration
** Buffer Groups
   The default behavior for tabbar-ruler is to group the tabs by frame.
   You can change this back to the old-behavior by:

   #+BEGIN_SRC emacs-lisp
     (tabbar-ruler-group-buffer-groups)
   #+END_SRC

   or by issuing the following code:

   #+BEGIN_SRC emacs-lisp
     (setq tabbar-buffer-groups-function 'tabbar-buffer-groups)
   #+END_SRC

   In addition, you can also group by projectile project easily by:

   #+BEGIN_SRC emacs-lisp
     (tabbar-ruler-group-by-projectile-project)
   #+END_SRC

** Key Bindings
   You can add key-bindings to change the current tab.  The easiest way
   to add the bindings is to add a key like:

   #+BEGIN_SRC emacs-lisp
     (global-set-key (kbd "C-c t") 'tabbar-ruler-move)
   #+END_SRC

   After that, all you would need to press is Control+c t and then the
   arrow keys will allow you to change the buffer quite easily. To exit
   the buffer movement you can press enter or space.
